#pragma once
#include "CoreMinimal.h"
#include "EActorType.generated.h"

UENUM(BlueprintType)
enum class EActorType : uint8 {
    ACTOR_TYPE_NONE,
    ACTOR_TYPE_PLAYER,
    ACTOR_TYPE_NPC,
    ACTOR_TYPE_SEQUENCER,
    ACTOR_TYPE_LUA_SPAWNED,
    ACTOR_TYPE_MAP_OBJECT,
    ACTOR_TYPE_MESH_DEPEND_CAMERA,
    ACTOR_TYPE_AI_MARKER,
    ACTOR_TYPE_ACTION_OBJECT,
    ACTOR_TYPE_COMMAND_COLLISION,
    ACTOR_TYPE_MAP_SOUND_SOURCE,
    ACTOR_TYPE_SCREEN_SHOT,
    ACTOR_TYPE_DYNAMIC_BURNABLE_OBJECT,
    ACTOR_TYPE_EFFECT_BASE,
    ACTOR_TYPE_MAX UMETA(Hidden),
};

