#pragma once
#include "CoreMinimal.h"
#include "ENeweraFlipbookOverrideType.generated.h"

UENUM(BlueprintType)
enum class ENeweraFlipbookOverrideType : uint8 {
    DEFAULT,
    COLOR_A,
    COLOR_B,
    COLOR_C,
    COLOR_D,
    COLOR_E,
    COLOR_F,
    COLOR_G,
    COLOR_H,
    BIGBOSS,
    RANK2,
    RANK3,
    BIRD,
    BIRD_RANK2,
    BIRD_RANK3,
    BIRD_BOW,
    HORSE,
    HORSE_RANK2,
    HORSE_RANK3,
    HORSE_TYPE_A,
    HORSE_TYPE_A_RANK2,
    HORSE_TYPE_A_RANK3,
    HORSE_TYPE_B,
    HORSE_TYPE_B_RANK2,
    HORSE_TYPE_B_RANK3,
    HORSE_TYPE_C,
    HORSE_TYPE_C_RANK2,
    HORSE_TYPE_C_RANK3,
    HORSE_TYPE_D,
    HORSE_TYPE_D_RANK2,
    HORSE_TYPE_D_RANK3,
    MASK,
    HORSEMASK,
    HORSEMASK_RANK2,
    HORSEMASK_RANK3,
    DISGUISE,
    BENEFIT_RANK2,
    BENEFIT_RANK3,
    FREEDOM_RANK2,
    FREEDOM_RANK3,
    MORAL_RANK2,
    MORAL_RANK3,
    BOW,
    BOW_RANK3,
    DAGGER,
    DAGGER_RANK3,
    SPEAR,
    SPEAR_RANK3,
    SWORD,
    SWORD_RANK3,
    SHIELD,
    SHIELD_RANK3,
    BOOK,
    BOOK_RANK3,
    ROD,
    ROD_RANK3,
    WAND,
    WAND_RANK3,
};

